staff_db = [
    {
        "id": 1,
        "role": "admin",
        "name": "Glory ThankGod",
        "email": "work.bildup@gmail.com",
        "password": "1234",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 2,
        "role": "driver",
        "name": "John",
        "email": "john.doe@gmail.com",
        "password": "0000",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 3,
        "role": "admin",
        "name": "Sara",
        "email": "john.doe2@gmail.com",
        "password":"9990",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 4,
        "role": "cook",
        "name": "Doe John",
        "email": "dave.doe@gmail.com",
        "password": "6675",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 5,
        "role": "cook",
        "name": "Dele Ayo",
        "email": "jide.doe@gmail.com",
        "password":"8604",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 6,
        "role": "accountant",
        "name": "Jude Ade",
        "email": "ade.doe@gmail.com",
        "password": "6543",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 7,
        "role": "driver",
        "name": "Chuks Emeka",
        "email": "emeka.doe@gmail.com",
        "password": "9098",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 8,
        "role": "driver",
        "name": "Femi Kuti",
        "email": "femi.kutz@gmail.com",
        "password": "4443",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 9,
        "role": "receptionist",
        "name": "Tunde Bakare",
        "email": "tunde@gmail.com",
        "password": "3210",
        "salary": None,     
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    },
    {
        "id": 10,
        "role": "security",
        "name": "Mike Tyson",
        "email": "mike@gmail.com",
        "password": "7777",
        "salary": None,
        "hire_date": None,
        "is_active": True,
        "age": None,
        "address": None,
        "phone_number": None
    }

]
